title: ChicaGoLang
description: This is a group for anyone interested in using Google's Go programming language for fun and profit.
baseurl: ""
url: http://chicagolang.com
github_username:  chicagolang
meetup_url: http://www.meetup.com/ChicaGoLang
permalink: /:title
markdown: kramdown
sass:
  sass_dir: assets/css